### ISSUE TITLE
cyclicExpand.previous?

### ISSUE THREAD

**Issue by huyz** [benjamin-thomas/vscode-cyclic-expand#1]
Why not the other direction?

**Comment by benjamin-thomas** [comment]
Yes it'd be nice to have, I don't have time to work on this at the moment though.

It doesn't look like a straight forward change, see [documentRippleScanner](https://github.com/benjamin-thomas/vscode-cyclic-expand/blob/51713356d59ea010ad07b0772a8b49ef318c0733/src/documentRippleScanner.ts).

Considering the list below, the original author intended for the completion to cycle this way: 

- milk
- mild
- mist
- mistery

```
mist
milk
mil<CURSOR_HERE>
mild
mistery
```

So at the moment, we can only "march forward", in a "ripple" fashion (which I don't like).

**Comment by huyz** [comment]
Oh it's supposed to work like a see-saw?  Hmm, that's odd.

**Comment by benjamin-thomas** [comment]
Yep :)

I find the fuzzy search excellent though so I'll probably dig into this at some point. It's a little annoying as-is.

**Comment by benjamin-thomas** [comment]
Feature implemented by @stagas (thanks) and published in v.0.0.4
